---
title: "Lab 4"
author: "Alex Baryiames"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    toc: true
    toc_float: true
    toc_depth: 4
  
---


```{r setup, include=FALSE}
library(reticulate)
use_python('/path/to/python') #EDIT
knitr::opts_chunk$set(echo = TRUE)
```



[home](https://rsh249.github.io/applied_bioinformatics)


# Blog
We attempted to sequence a mixed DNA sample using a minion sequencer. First, we started by extracting gDNA from a culture of E. coli, and an unknonw lichin sample. The two were mixed together under the assumption that the species present in both samples would be mutually exclusive. gDNA concentration was measured using a cubit and was sufficiant for sequencing according to nanopore protocall. However, before we loaded the sample into the nanopore we were unable to remove a large air bubble from the flowcell. When the sample was loaded, it pushed the air bubble over the pores and perminantly destroyed them. This resulted in only a few active pores and sequencing failed. For our second sample, the air bubble was removed and sequencing was successful, however, the run was aborted becuase the quality of the DNA had degraded. Degraded DNA is insuitable for nanopore sequencing because the basecalling software screens out basecalls which may be statiscially inaccurate.

In the future, we must take extra steps to ensure that the quality of our DNA is sutable for sequencing. This includes running a gel to determine the length of the DNA sequence (oxford nanopore suggests ~20kb) as well as measuring the protein/dsDNA and RNA/dsDNA ratio.



## No R code this lab- just Nanopore sequencing.

```{R, eval=TRUE}

```





[home](https://rsh249.github.io/applied_bioinformatics)
