---
title: "Projects"
author: "Prof. Harbert"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    toc: true
    toc_float: true
    toc_depth: 4
  
---


```{r setup, include=FALSE}
library(reticulate)
use_python('/path/to/python') #EDIT
knitr::opts_chunk$set(echo = TRUE)
```



[home](https://rsh249.github.io/applied_bioinformatics)


# Projects

The primary evaluation in this course is the Project. You will be developing a term project around reproducing an analysis of Nanopore DNA sequencing data from recent primary research literature.

The course project will consist of:

1)	A written project proposal(20pts)

2)	An oral presentation of the proposed research(30pts)

3)	Code to reproduce the analyses(50pts)

4)	A final project presentation(200pts)

5)	A Term Paper describing your work and findings(200pts)


In addition you will produce two blog posts later in the semester about your project progress.

The project assignments account for 50% of your course grade.

# Proposals

Guidance on the proposal development can be found [here](https://rsh249.github.io/applied_bioinformatics/BIO332_Project_proposal.pdf) and on eLearn.

# Today

In lab today you will pick a research study to work on. This can be from the preliminary list of papers we gathered last week or from something new you find. 

Once you have picked a paper you need to find and add to the shared projects spreadsheet:

1) Your username as it appears on the server

2) The paper title, publication year, first author, journal, and stable DOI link.

3) Locate the original data for the study. Get this approved to be sure that you have the primary data and not processed data. Add links to individual files as a list of comma separated URLs. (If more than 8 files consult your instructor) Do NOT download files yet, we will bulk download all files for these projects once we have a complete list.

4) List ALL software the paper describes using. Look for the source to download each piece of software (keep these for your notes). Develop a separate software notes file that includes the software packages listed, where you can download each, and a short description of what each one does.

5) Come up with a code-name for your project to use on the server and in the Git repository as a folder name. This needs to be one word or multiple words separated by an "_" underscore.







[home](https://rsh249.github.io/applied_bioinformatics)
